build:
  install: python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt
run:
  start: . /opt/venv/bin/activate && gunicorn -w 4 -b :5010 backend.certificate_generator:app
